# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deliwer-ecosystem"
client_id = "YOUR_CLIENT_ID"
application_url = "https://your-actual-vercel-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers,write_draft_orders,read_draft_orders,write_inventory,read_inventory,write_fulfillments,read_fulfillments"

[auth]
redirect_urls = [
  "https://deliwer-ecosystem.vercel.app/auth/callback",
  "https://deliwer-ecosystem.vercel.app/auth/shopify/callback",
  "https://deliwer-ecosystem.vercel.app/shopify/auth/verify"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "orders/paid" ]
uri = "https://deliwer-ecosystem.vercel.app/shopify/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = [ "customers/create" ]
uri = "https://deliwer-ecosystem.vercel.app/shopify/webhooks/customers/create"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://deliwer-ecosystem.vercel.app/shopify/webhooks/app/uninstalled"

[pos]
embedded = false

[[build.commands]]
command = "npm run build"

[build.automatically_update_urls_on_dev] = true
[build.dev_store_url] = "deliwer.myshopify.com"

[app_proxy]
url = "https://deliwer-ecosystem.vercel.app"
subpath = "apps/deliwer"
prefix = "apps"