# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deliwer-ecosystem"
client_id = "YOUR_CLIENT_ID"
application_url = "https://deliwer-ecosystem.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://deliwer-ecosystem.vercel.app/auth/callback",
  "https://deliwer-ecosystem.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[[build.commands]]
command = "npm run build"

[build.automatically_update_urls_on_dev] = true
[build.dev_store_url] = "deliwer.myshopify.com"