// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reverse-auction/ReverseAuctionPortal.tsx": () => import("../components/mockups/reverse-auction/ReverseAuctionPortal.tsx")
};
